### ISSUE TITLE
Server configuration

### ISSUE THREAD

**Issue by coalyonysh** [AsenOsen/SSHCenter#1]
Good evening!
Plaese explain more about the configuration process.
My config. json:
```
{       "default" : {
                "keyfile": "",
                "password": "",
                "user": ""
},

        "servers": {
                "local": {
                        "host": "192.168.55.5"
                },
                "ubuntu19": {
                        "host": "192.168.88.4"
                },
                "gateway20": {
                        "host": "192.168.55.1"
                }
        },

        "groups": {
                "all": [".*"],
                "local": ["local"],
                "remoteUbuntu19": ["ubuntu19"],
                "remoteUbuntu20": ["gateway20"]
        }
}
```
Do I need to fill in the fields in the default section?
In what format do I need to send the ssh key when adding a user?
When running the command:
`sudo python3 sshcenter.py -g local add test "ssh-rsa AAAAB3Nz...vVP0E= test@test"`

I get 
Exception: Authentification failed for server: local

**Comment by AsenOsen** [comment]
Hi!
SSH key goes in `keyfile` field as path to file in local system. This field can be located as in `default` section (applies to all) as in each item of `servers` section (applied individually). If `keyfile` is password-protected then password specified in `password` field.

When passing sshkey in `add` command, use separatelly type `ssh-rsa` and base64-encoded key part. Default key type is `ssh-rsa`, so it is unnessesary to specify.

**Comment by AsenOsen** [comment]
Example:

```
./sshcenter.py -g local add <base64-encoded-part> test@test
```
